### ISSUE TITLE
DateTimeOffset serialization failure

### ISSUE THREAD

**Issue by anderslyman** [polenter/SharpSerializer#17] opened 2021-12-13 17:10 UTC
When serializing/deserializing `DateTimeOffset` properties, the date is set to the default value of `1/1/0001 12:00:00 AM +00:00`.
Conversely, `DateTime` properties work as expected.

LINQPad script: http://share.linqpad.net/i8covu.linq

```
void Main()
{
	var dtA = new DateTimeOffsetExample { Date = DateTimeOffset.Now };
	var dtB = new DateTimeExample { Date = DateTime.Now };

	var bytesA = ObjectToByteArray(dtA);
	ByteArrayToObject<DateTimeOffsetExample>(bytesA).Dump();

	var bytesB = ObjectToByteArray(dtB);
	ByteArrayToObject<DateTimeExample>(bytesB).Dump();
}

public class DateTimeExample
{
	public DateTime Date { get; set; }
}

public class DateTimeOffsetExample
{
	public DateTimeOffset Date { get; set; }
}

public static byte[] ObjectToByteArray(object obj)
{
	if (obj == null)
	{
		return Array.Empty<byte>();
	}

	using var ms = new MemoryStream();
	var serializer = new SharpSerializer(true);
	serializer.Serialize(obj, ms);

	return ms.ToArray();
}

public static T ByteArrayToObject<T>(byte[] arrBytes)
{
	if (arrBytes == null)
	{
		return default(T);
	}

	using var memStream = new MemoryStream();
	memStream.Write(arrBytes, 0, arrBytes.Length);
	memStream.Seek(0, SeekOrigin.Begin);
	var serializer = new SharpSerializer(true);
	var obj = serializer.Deserialize(memStream);

	return (T)obj;
}
```

Yields:
![image](https://user-images.githubusercontent.com/1380857/145857102-ceb04e68-719a-4921-847f-d6085e797674.png)

**Comment by anderslyman** [comment] 2021-12-13 17:37
PR'd - I realize this repo has seen no activity in 4 years, but it's here if someone wants it.

**Comment by AntiTenzor** [comment] 2021-12-15 07:58
> PR'd - I realize this repo has seen no activity in 4 years, but it's here if someone wants it.

Thank you very much for this PR!
We'll hope it will be merged in main. =)

**Comment by AntiTenzor** [comment] 2021-12-15 08:22
There is one more critical error. This serializer does not preserve **Kind** property.

Let's modify your example:
```
var dtB = new DateTimeExample { Date = DateTime.**UtcNow** };
```

Then
```
DateTimeExample actualDt = ByteArrayToObject<DateTimeExample>(bytesB);
```

Now let's examain **actualDt.Date.Kind** :

```
if (actualDt.Date.Kind != DateTimeKind.Utc)
    throw new InvalidOperationException($"Expected Kind is UTC, but it is '{actualDt.Date.Kind}'!");
```

**Comment by polenter** [comment] 2021-12-28 12:00
I've just merged the PR of @anderslyman. Thanks!
Additional tests report no errors concerning XML serialization of DateTimeKind. However, there are errors during the binary serialization, confirming the problem reported by @AntiTenzor.
The problem is extracted there: #20

**Closed by polenter** 2021-12-28 12:00 UTC
